#!/bin/bash

bspc monitor HDMI-0 -d I III II
bspc monitor DVI-I-1 -d V IV VI
bspc monitor DVI-D-0 -d VIII VII IX
bspc config window_gap                   10
bspc config left_padding                  5
bspc config right_padding                 5
bspc config bottom_padding                5

bspc config split_ratio                0.50
bspc config borderless_monocle         true
bspc config gapless_monocle            true
bspc config focus_by_distance         false
bspc config history_aware_focus        true
bspc config focus_follows_pointer     false
bspc config pointer_follows_focus     false
bspc config click_to_focus             true
bspc config adaptive raise             true
bspc config center_pseudo_tiled        true
bspc config pointer_modifier        control
bspc config pointer_action2         resize_corner
bspc config initial_polarity       SECOND_CHILD 


bspc config normal_border_color   "#131313"
bspc config focused_border_color  "#131313"
bspc config presel_feedback_color "#131313"

bspc config top_padding                  25

compton -b &
feh --bg-scale ~/Pictures/wallhaven-26479.jpg &
$HOME/.config/polybar/launch.sh
dunst &
xrdb ~/.Xresources
